# Generated by Django 5.0.6 on 2024-07-17 16:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "birthday",
                    models.DateField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(2000, 1, 1), "Must be born in 2001-01"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
