# Generated by Django 5.0.6 on 2024-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.ImageField(
                default="media/default.png", upload_to="media/topics/"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
