# Generated by Django 5.0.6 on 2024-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_alter_topic_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="image",
        ),
        migrations.AddField(
            model_name="topic",
            name="image_topic",
            field=models.ImageField(default="default.png", upload_to="topics/"),
        ),
    ]
