# Generated by Django 5.0.6 on 2024-07-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_customer",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_owner",
        ),
        migrations.AddField(
            model_name="account",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "Customer"), (2, "Owner")], default=1
            ),
        ),
    ]
