# Generated by Django 5.0.6 on 2024-07-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_remove_account_user_type_account_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.role",
            ),
        ),
    ]
