# Generated by Django 5.0.6 on 2024-07-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.role",
            ),
        ),
    ]
