# Generated by Django 5.0.6 on 2024-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
